markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Jason Draper
url: http://drapergeek.com
description: web developer / geek
twitter: drapergeek
github: drapergeek
gravatar_url: http://www.gravatar.com/avatar/620e689d6045838491aa0f2a4d4b2004.png 
